#!/usr/bin/env bash
# 配布物に含まれる依存ライブラリのライセンスを THIRD-PARTY-NOTICES.txt に書き出す。
# `pnpm notices` から呼ばれる。依存を足したり上げたりしたら流し直してコミットする
# (main.rs のテストが、直接依存がこのファイルに載っているかを見る)。
#
# Rust 側は cargo-about (`cargo install cargo-about --locked --features cli`)、
# 設定は src-tauri/about.toml、書式は src-tauri/about.hbs。
# npm 側は vite が bundle する runtime だけを node_modules から読む:
#   - package.json の dependencies
#   - BUNDLED_RUNTIME に列挙したもの。svelte は devDependencies にあるが、コンパイル後の
#     コンポーネントが svelte の runtime (svelte/internal/client) を import するので
#     bundle に入る。clsx はその runtime が class 属性の組み立てに import する
#     (`vite build --minify false` の出力で確認した)。svelte の esm-env は定数だけで
#     tree-shake されて残らないので載せない
# devDependencies のビルドツール (vite / tailwindcss 等) は配布物に入らないので載せない。
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"

if ! cargo about --version >/dev/null 2>&1; then
  echo "Error: cargo-about is not installed. Run: cargo install cargo-about --locked --features cli" >&2
  exit 1
fi
if [ ! -d node_modules ]; then
  echo "Error: node_modules is missing. Run: pnpm install" >&2
  exit 1
fi

# 同じディレクトリに作る。別ファイルシステムの /tmp からの mv はコピーになり、途中で
# 止まると壊れた出力が残る
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

{
  cat <<'HEADER'
THIRD-PARTY NOTICES

Toneweave bundles the open source libraries listed below. Each entry gives the
license, the packages it applies to, and the license text as shipped by the
package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.

################################################################################
# JavaScript packages (bundled into the web view)
################################################################################

HEADER

  node - <<'NODE'
const fs = require("fs");
const path = require("path");
// [名前, そのパッケージを探し始めるディレクトリ]。pnpm の node_modules は平坦ではないので、
// svelte の依存 (clsx) は svelte の実体の隣から探す
const BUNDLED_RUNTIME = [
  ["svelte", "node_modules"],
  ["clsx", path.join(fs.realpathSync("node_modules/svelte"), "..")],
];
const deps = Object.keys(JSON.parse(fs.readFileSync("package.json", "utf8")).dependencies)
  .map((name) => [name, "node_modules"])
  .concat(BUNDLED_RUNTIME)
  .sort(([a], [b]) => a.localeCompare(b));
for (const [name, base] of deps) {
  const dir = path.join(base, name);
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
  const repo = typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url;
  // LICENSE.spdx のような SPDX のメタデータは本文ではないので除く
  const files = fs
    .readdirSync(dir)
    .filter((f) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(f) && !/\.spdx$/i.test(f))
    .sort();
  console.log("=".repeat(80));
  console.log(`License: ${pkg.license}`);
  console.log("");
  console.log("Used by:");
  console.log(`  ${name} ${pkg.version}${repo ? ` (${repo})` : ""}`);
  console.log("");
  if (files.length === 0) {
    // 本文が同梱されていない package。表記と配布元だけ残す
    console.log("The package does not ship its license text; see the repository above.");
    console.log("");
    continue;
  }
  for (const f of files) {
    if (files.length > 1) console.log(`--- ${f} ---`);
    console.log(fs.readFileSync(path.join(dir, f), "utf8").replace(/\s+$/, ""));
    console.log("");
  }
}
NODE

  cat <<'HEADER'
################################################################################
# Rust crates (compiled into the binary)
################################################################################

HEADER

  # --fail: ライセンスを特定できない crate があれば警告で省略せず失敗させる
  cargo about generate --manifest-path src-tauri/Cargo.toml --locked --fail src-tauri/about.hbs
} > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
